name: build wheel
on: [workflow_dispatch]
jobs:
  wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: docker/Dockerfile
          tags: cust-many-linux:latest
      - uses: shrink/actions-docker-extract@v2
        id: extract
        with:
          image: cust-many-liunx:latest
          path: /app/wheelhouse/
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: ${{ steps.extract.outputs.destination }}
