name: manylinux
on: [workflow_dispatch]
jobs:
  pep513:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install build dependencies
        run: |
          apt-get install xapian-core
          pip install --upgrade pip setuptools wheel build sphinx
      - name: Build wheel
        run: |
          python setup.py bdist_wheel
