name: wheel
on: [workflow_dispatch]
jobs:
  wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install build dependencies
        run: |
          sudo apt-get install libxapian-dev
          pip install --upgrade pip setuptools wheel build sphinx twine
      - name: Build wheel
        run: |
          python setup.py bdist_wheel
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}